name: Commit Lint
on:
  pull_request:

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.1.4
      - run: pnpm install
      - run: echo "${{ github.event.pull_request.title }}" | pnpm commitlint
